# Generated by Django 5.0.2 on 2024-02-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aquarium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aquarium Name",
                    ),
                ),
                ("volume", models.IntegerField(verbose_name="Volume (L)")),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Lange (cm)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Breite (cm)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Höhe (cm)",
                    ),
                ),
                ("created_at", models.DateField(verbose_name="Erstellt am")),
                (
                    "updated_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Redesigned am"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aquarium",
                "verbose_name_plural": "Aquarien",
                "ordering": ["-created_at"],
            },
        ),
    ]
