# Generated by Django 5.0.2 on 2024-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquarium", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquarium",
            name="created_at",
            field=models.DateField(
                help_text="Datum der Erstellung.", verbose_name="Erstellt am"
            ),
        ),
        migrations.AlterField(
            model_name="aquarium",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name des Aquariums. Falls nicht angegeben, wird ein Standardname verwendet.",
                max_length=100,
                null=True,
                verbose_name="Aquarium Name",
            ),
        ),
        migrations.AlterField(
            model_name="aquarium",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Datum des letzten Redesigns, falls zutreffend.",
                null=True,
                verbose_name="Redesigned am",
            ),
        ),
    ]
