# Generated by Django 5.0.2 on 2024-02-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquarium", "0002_alter_aquarium_created_at_alter_aquarium_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquarium",
            name="volume",
            field=models.PositiveIntegerField(verbose_name="Volume (L)"),
        ),
    ]
