# Generated by Django 5.0.2 on 2024-02-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name des Fisches.",
                        max_length=100,
                        verbose_name="Name des Fisches",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Anzahl der Fische.", verbose_name="Anzahl"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Bild des Fisches.",
                        null=True,
                        upload_to="fish/",
                        verbose_name="Bild",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Datum der Setzung.", verbose_name="Gesetzt am"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Verfügbar"),
                ),
            ],
            options={
                "verbose_name": "Fisch",
                "verbose_name_plural": "Fische",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Died",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Anzahl der verstorbenen Fische.",
                        verbose_name="Anzahl",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Datum des Todes.", verbose_name="Gestorben am"
                    ),
                ),
                (
                    "fish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="died",
                        to="fish.fish",
                        verbose_name="Fisch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tod",
                "verbose_name_plural": "Tode",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Anzahl der verkauften Fische.", verbose_name="Anzahl"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preis des Fisches.",
                        max_digits=10,
                        verbose_name="Preis (€)",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Datum des Verkaufs.", verbose_name="Verkauft am"
                    ),
                ),
                (
                    "fish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="fish.fish",
                        verbose_name="Fisch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verkauf",
                "verbose_name_plural": "Verkäufe",
                "ordering": ["-created_at"],
            },
        ),
    ]
